import GlobalProvider from "./GlobalProvider";
import "./globals.css";
import "./styles.css";

export const metadata = {
  title: "AutoDiagonoza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
