export const tools = [
  { value: "Alientech K-tag", label: "Alientech K-tag" },
  { value: "Alientech Kess v2", label: "Alientech Kess v2" },
  { value: "Alientech Kess v3", label: "Alientech Kess v3" },
  { value: "Alientech Powergate", label: "Alientech Powergate" },
  { value: "Autotuner Bench", label: "Autotuner Bench" },
  { value: "Autotuner Boot Mode", label: "Autotuner Boot Mode" },
  { value: "Autotuner OBD", label: "Autotuner OBD" },
  { value: "bFlash", label: "bFlash" },
  { value: "bFlash Bench", label: "bFlash Bench" },
  { value: "bFlash BOOT", label: "bFlash BOOT" },
  { value: "bFlash OBD", label: "bFlash OBD" },
  { value: "Bitbox", label: "Bitbox" },
  { value: "BS OBD", label: "BS OBD" },
  { value: "BS toolbox", label: "BS toolbox" },
  { value: "BS Tricore Boot tool", label: "BS Tricore Boottool" },
  { value: "CMD BDM", label: "CMD BDM" },
  { value: "CMD Bench", label: "CMD Bench" },
  { value: "CMD OBD", label: "CMD OBD" },
  { value: "CMD Toolbox", label: "CMD Toolbox" },
  { value: "CMD Tricore Boot tool", label: "CMD Tricore Boottool" },
  { value: "Dimsport MyGenius", label: "Dimsport MyGenius" },
  { value: "Dimsport New Genius", label: "Dimsport New Genius" },
  { value: "Dimsport New Trasdata", label: "Dimsport New Trasdata" },
  { value: "Eprom programmer", label: "Eprom programmer" },
  { value: "EVC BDM", label: "EVC BDM" },
  { value: "EVC BSL", label: "EVC BSL" },
  { value: "Femto", label: "Femto (Bmw Tool)" },
  { value: "FGtech", label: "FGtech" },
  { value: "Frieling i-Boot", label: "Frieling i-Boot" },
  { value: "Frieling i-Flash", label: "Frieling i-Flash" },
  { value: "Frieling SPI Wizard", label: "Frieling SPI Wizard" },
  { value: "Galetto", label: "Galetto" },
  { value: "HP Tuners", label: "HP Tuners" },
  { value: "Magic Motorsport Flex OBD", label: "Magic Motorsport Flex OBD" },
  {
    value: "Magic Motorsport Flex Bench",
    label: "Magic Motorsport Flex Bench",
  },
  { value: "Magic Motorsport Flex Boot", label: "Magic Motorsport Flex Boot" },
  { value: "MAGPRO Bench/Flex", label: "Magic Motorsport MAGPRO Bench/Flex" },
  { value: "MAGPRO Boot Mode", label: "Magic Motorsport MAGPRO Bootmode" },
  { value: "MAGPRO OBD", label: "Magic Motorsport MAGPRO OBD" },
  { value: "MPPS", label: "MPPS" },
  { value: "PCM Flash", label: "PCM-Flash" },
  { value: "Pemicro Nexus Debugger", label: "Pemicro Nexus Debugger" },
  { value: "Piasini Serial Suite", label: "Piasini Serial Suite" },
  { value: "Other", label: "Others" },
];

export const manufactureYears = [
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003" },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
  { value: "1999", label: "1999" },
  { value: "1998", label: "1998" },
  { value: "1997", label: "1997" },
  { value: "1996", label: "1996" },
  { value: "1995", label: "1995" },
  { value: "1994", label: "1994" },
  { value: "1993", label: "1993" },
  { value: "1992", label: "1992" },
  { value: "1991", label: "1991" },
  { value: "1990", label: "1990" },
];

export const gearTypes = [
  { value: "Manual Gear", label: "Manual Transmission" },
  { value: "Auto Gear", label: "Automatic Transmission" },
];

export const workTypes = [
  { value: "original", label: "Original", tokens: 0.3 },
  { value: "stage_1", label: "Stage 1", tokens: 0.8 },
  { value: "Only Options", label: "Only Options", tokens: 0.5 },
  { value: "Stage 1+Options", label: "Stage 1+Options", tokens: 1.1 },
  { value: "Stage 2", label: "Stage 2", tokens: 1.4 },
  { value: "mappack", label: "Mappack", tokens: 0.8 },
];

export const tuningOptions = [
  { value: "adblue", label: "Adblue (+0.2)" },
  { value: "dpf", label: "DPF" },
  { value: "egr", label: "EGR" },
  { value: "maf", label: "MAF" },
  { value: "lambda", label: "Lambda" },
  { value: "exh", label: "Exh Flap" },
  { value: "burbles", label: "Burbles (+0.2)" },
  { value: "vmax", label: "Vmax" },
  { value: "dtc", label: "DTC" },
  { value: "hot", label: "Hot Start" },
  { value: "tm", label: "Torque Monitoring" },
  { value: "sum", label: "Checksum (+0.1)" },
];
